# Generated by Django 5.2.12 on 2026-03-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('Proposal', 'Proposal'), ('Development', 'Development'), ('Review', 'Review'), ('Finalization', 'Finalization')], default='Proposal', max_length=30),
        ),
    ]
