# Generated by Django 5.2.12 on 2026-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_alter_contribution_id_alter_verification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='work_type',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Research', 'Research'), ('Design', 'Design'), ('Documentation', 'Documentation'), ('Testing', 'Testing'), ('Presentation', 'Presentation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
