# Generated by Django 5.2.12 on 2026-03-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_alter_contribution_id_alter_contribution_work_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='contributions/'),
        ),
    ]
