# Generated by Django 6.0 on 2026-02-18 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fairness_score', models.FloatField(default=0.0)),
                ('contribution_distribution', models.JSONField(default=dict)),
                ('imbalance_warning', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('highest_contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lowest_contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='teams.team')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
