# Generated by Django 4.2.28 on 2026-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_teamanalytics_date_teamanalytics_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamanalytics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
