# Generated by Django 5.2.12 on 2026-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_teamanalytics_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamanalytics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
