# Generated by Django 5.2.12 on 2026-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_user_type_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEAM_LEAD', 'Team Lead'), ('INSTRUCTOR', 'Instructor')], default='STUDENT', max_length=15),
        ),
    ]
